#%RAML 1.0 NamedExample
value: |
  {
    "user": "john doe",
    "productName": "Short Sleeve Shirt",
    "productColor": "black",
    "productSize": "small",
    "productDesc": "Lightweight short sleeve shirt with MuleSoft logo.",
    "imageUrl": "https://swag.mulesoft.com/images/items/MU00-5037.jpg",
    "location": "locationId"
  }